version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./restframework-todo:/restframework-todo"
    command: >
      sh -c "python manage.py runserver 0:8000"
