# Generated by Django 2.2.12 on 2020-05-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
